num = int(input('Digite um número: '))
um = num * 1
dois = num * 2
tres = num * 3
quatro = num * 4
cinco = num * 5
seis = num * 6
sete = num *7
oito = num * 8
nove = num * 9
print('0x{}=0'.format(num))
print('1x{}={}'.format(num, um))
print('2x{}={}'.format(num, dois))
print('3x{}={}'.format(num, tres))
print('4x{}={}'.format(num, quatro))
print('5x{}={}'.format(num, cinco))
print('6x{}={}'.format(num, seis))
print('7x{}={}'.format(num, sete))
print('8x{}={}'.format(num, oito))
print('9x{}={}'.format(num, nove))